<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit97090621e2671db665fc4f042eb095de
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WDLDemo\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WDLDemo\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit97090621e2671db665fc4f042eb095de::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit97090621e2671db665fc4f042eb095de::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit97090621e2671db665fc4f042eb095de::$classMap;

        }, null, ClassLoader::class);
    }
}
